### ISSUE TITLE
The "default" queue configuration does not exist.

### ISSUE THREAD

**Issue by jonylulu** [scherersoftware/cake-websocket#10]
[root@m_netshare_com_cn pm]# bin/cake websocket_server
Exception: The "default" queue configuration does not exist. in [/home/nsweb/html/update_yue-lian_com/pm/vendor/josegonzalez/cakephp-queuesadilla/src/Queue/Queue.php, line 220]
2018-03-22 15:56:26 Error: [InvalidArgumentException] The "default" queue configuration does not exist. in /home/nsweb/html/update_yue-lian_com/pm/vendor/josegonzalez/cakephp-queuesadilla/src/Queue/Queue.php on line 220
Stack Trace:
#0 /home/nsweb/html/update_yue-lian_com/pm/vendor/josegonzalez/cakephp-queuesadilla/src/Queue/Queue.php(250): Josegonzalez\CakeQueuesadilla\Queue\Queue::_buildEngine('default')
#1 /home/nsweb/html/update_yue-lian_com/pm/vendor/scherersoftware/cake-websocket/src/Shell/WebsocketServerShell.php(58): Josegonzalez\CakeQueuesadilla\Queue\Queue::engine('default')
#2 /home/nsweb/html/update_yue-lian_com/pm/vendor/cakephp/cakephp/src/Console/Shell.php(507): Websocket\Shell\WebsocketServerShell->main()
#3 /home/nsweb/html/update_yue-lian_com/pm/vendor/cakephp/cakephp/src/Console/CommandRunner.php(141): Cake\Console\Shell->runCommand(Array, true)
#4 /home/nsweb/html/update_yue-lian_com/pm/bin/cake.php(12): Cake\Console\CommandRunner->run(Array)
#5 {main}

**Comment by cleptric** [comment]
@jonylulu Could you please explain your issue a little bit further?

**Comment by jonylulu** [comment]
it's work~sorry,I can't speak too much English.
Thanks

in bootstrap.php
use Josegonzalez\CakeQueuesadilla\Queue\Queue;
Queue::config('default', [
    'engine' => 'josegonzalez\Queuesadilla\Engine\MysqlEngine',
    'database'=>'xx',
    'host'=>'xx',
    'user'=>'xx',
    'pass'=>'xx'
]);
