### ISSUE TITLE
Invalid Websocket event config.

### ISSUE THREAD

**Issue by vivek-addon** [scherersoftware/cake-websocket#13]
I installed this plugin in cakephp 3.

When i am going to create event by this code then i am getting "Invalid Websocket event config" error.

 Websocket::publishEvent('order', ['order' => $res]);

**Comment by felixkempf** [comment]
Check your `websocket_events.php` config. It should contain something like:

```
    'order' => [
        'audience' => [
            'includeAllNotAuthenticated' => false,
            'includeAllAuthenticated' => false,
        ],
    ],
```
