### ISSUE TITLE
Getting console error "No JS Controller instance passed"

### ISSUE THREAD

**Issue by cercos** [scherersoftware/cake-websocket#6]
I followed the docs install but I am getting a **No JS Controller instance passed** in console.  I'm not sure where I am suppose to pass the FrontendBridge the controller.

**Comment by cleptric** [comment]
Have you also setup https://github.com/scherersoftware/cake-frontend-bridge?
This part is missing from the docs, but this plugin relies on the `cake-frontend-bridge` package. We'll fix the README accordingly

**Comment by cercos** [comment]
Yeah that plugin is installed already.  I installed it when I saw it in requirements.

**Comment by wolfgang-stark** [comment]
Hey cercos, I've updated the readme of the frontend bridge (https://github.com/scherersoftware/cake-frontend-bridge/blob/master/README.md#7-add-main-content-classes) Just change your default.ctp as written in the readme and it should work
