### ISSUE TITLE
The "default" queue configuration does not exist. in [.../vendor/josegonzalez/cakephp-queuesadilla/src/Queue/Queue.php

### ISSUE THREAD

**Issue by aquaminer** [scherersoftware/cake-websocket#7]
`The "default" queue configuration does not exist. in [.../vendor/josegonzalez/cakephp-queuesadilla/src/Queue/Queue.php` Tell me please, I did everything according to the instructions but at performance `Websocket::publishEvent('userDataUpdated', ['editedUserId' => 12]);` error.

**Comment by aquaminer** [comment]
@wolfgang-braun waiting for your reply)

**Comment by wolfgang-stark** [comment]
@opkiler22789 You need to configure the app.php properly:
![screen shot 2017-08-10 at 18 48 28](https://user-images.githubusercontent.com/8513406/29181745-8ac2ef8c-7dfc-11e7-8ce7-b976cb3ee255.png)

**Comment by cleptric** [comment]
@opkiler22789 I'll close this for now. If you have any further questions fell free to reply to this issue 🙂

**Comment by yanisasan** [comment]
@wolfgang-braun 

'Queuesadilla' => [
        'default' => [
            'engine' => 'josegonzalez\Queuesadilla\Engine\MysqlEngine',
            'database'=>'xx',
            'host'=>'xx',
            'user'=>'xx',
            'pass'=>'xx',
        ],
    ],

i was wrote this in app.php but still same error..  can you help me..
thx

**Comment by wolfgang-stark** [comment]
@yanisasan please send me the obfuscated result of `debug(Cake\Core\Configure::read('Queuesadilla'));` and your composer.json and check whether you've  called `Queue::setConfig(Configure::consume('Queuesadilla'));`

**Comment by yanisasan** [comment]
i was put 
Queue::config('default', [
            'engine' => 'josegonzalez\Queuesadilla\Engine\MysqlEngine',
            'database'=>'xx',
            'host'=>'ip',
            'user'=>'xx',
            'pass'=>'xx',
            //'url' => 'mysql://username:password@localhost:80/database'
]);
in config/bootstrap.php
and the result no error again 

thanks
